name: todo_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI関連
  cupertino_icons: ^1.0.6

  # Firebase関連
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1

  # Google認証
  google_sign_in: ^6.2.1

  # ML Kit（最新バージョンに更新）
  google_mlkit_barcode_scanning: ^0.13.0
  google_mlkit_commons: ^0.9.0
  google_mlkit_digital_ink_recognition: ^0.13.0
  google_mlkit_entity_extraction: ^0.14.0
  google_mlkit_face_detection: ^0.12.0
  google_mlkit_face_mesh_detection: ^0.3.0
  google_mlkit_image_labeling: ^0.13.0
  google_mlkit_language_id: ^0.12.0
  google_mlkit_object_detection: ^0.14.0
  google_mlkit_pose_detection: ^0.13.0
  google_mlkit_selfie_segmentation: ^0.9.0
  google_mlkit_smart_reply: ^0.12.0
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_translation: ^0.12.0

  # 画像アップロード
  image_picker: ^1.0.7

  # OCR（画像からテキスト抽出）
  google_ml_kit: ^0.19.0

  # プッシュ通知
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  workmanager: ^0.5.1

  # 日付フォーマット
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

